services:
  nextapp-2:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: https://lc.envai.tr
        NEXT_PUBLIC_ASSISTANT_ID: google2

    container_name: envaichat
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'     # max 1 CPU core
          memory: 2G    # max 512 MB RAM
